project:
  type: website

website:
  title: "Niel Bauer Lab Notebook"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Experiments.qmd
        text: Experiments

format:
  html:
    theme: solar

editor: visual

